### ISSUE TITLE
データの定期更新機能

### ISSUE THREAD

**Issue by katsuyoshi** [asaba-zauberer/covid19-akita#40]
rakeコマンドでデータを更新できる様になりましたので、Githubのworkflow機能を使って定期的に更新することができるのではないかと思います。
トリガーとしてscheduleを用いればできそうに思います。

参考になるか分かりませんが、こちらに例を作ってみました。

https://github.com/katsuyoshi/covid19-akita/blob/daily_update/.github/workflows/daily_update.yml

データ更新の手作業を減らせますので検討いただければ幸いです。

**Comment by asaba-zauberer** [comment]
ご提案ありがとうございます。
検討させていただきます。

**Comment by asaba-zauberer** [comment]
一先ずdaily_update.ymlとして自動更新のワークフローを作成し追加しました。
・実際にデータに前日から変更があったケースを試行していない
・仮に毎日更新があった場合、ホスティングしているNetlifyの無料枠を超えるかも?
という状況で、まだ少し様子見なのでissueは閉じずに置きます。

**Comment by katsuyoshi** [comment]
対応ありがとうございます。
無理強いしませんので気が向いた時で大丈夫です。

**Comment by katsuyoshi** [comment]
[今回](https://github.com/asaba-zauberer/covid19-akita/pull/57)の様にホームページの構成が変わった場合に気づきにくくなるので、自動にしない方がいいですね。
お願いして済みません。
しばらくは今まで通り手作業で進めたいと思いますので、クローズしていただいて結構です。

**Comment by asaba-zauberer** [comment]
サイト移行に伴いクローズいたします
